language: android
jdk:
  - oraclejdk7
  - openjdk7
  
before_install:
  - sudo apt-get update
  - sudo apt-get install php5 
  - curl -sS https://getcomposer.org/installer | php
  - sudo mv composer.phar /usr/local/bin/phar

install:
  - composer install --no-interaction

android:
  components:
    - build-tools-19.0.0
    - android-19

script:
  - bash gradlew uploadArchives
  - ./vendor/bin/phpunit

