language: android
jdk:
  - oraclejdk7
  - openjdk7
  
install:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --no-interaction

android:
  components:
    - build-tools-19.0.0
    - android-19

script:
  - bash gradlew uploadArchives
  - ./vendor/bin/phpunit

